import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "./provider"
import { Box } from "@chakra-ui/react"
import { ImageCustom } from "@/components/Image/Image"
import logo from "../asset/image/logo.png"
import Button from "@/components/Button"
import { RiLogoutBoxFill, RiOutletFill } from "@remixicon/react"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "ระบบการจัดการวิชาเทียบโอนหน่วยกิต",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box display="flex">
            <Box
              display="flex"
              position="fixed"
              flexDirection="column"
              padding="20px"
              minW="200px"
              height="100vh"
              borderWidth="1px"
              borderColor="black"
              alignItems="center"
              backgroundColor="#000080"
              textColor="white"
              gap="24px"
            >
              <ImageCustom
                width={220}
                height={108}
                src={logo}
                alt={"logo"}
              />
              <Box
                display="flex"
                flexDirection="column"
                justifyContent="space-between"
                height="100%"
              >
                <Box
                  paddingY="8px"
                  paddingX="60px"
                  backgroundColor="white"
                  color="black"
                  borderRadius="8px"
                >
                  เทียบโอนรายวิชา
                </Box>
                <Button
                  label={"ออกจากระบบ"}
                  color="white"
                  borderRadius="8px"
                  backgroundColor="#FF4E4E"
                  leftIcon={<RiLogoutBoxFill color="#FFFFFF" />}
                />
              </Box>
            </Box>
            <Box
              w="100%"
              paddingLeft="60px"
            >
              {children}
            </Box>
          </Box>
        </Providers>
      </body>
    </html>
  )
}
